spring:
  application:
    name: spring-cloud-config-server-9092
  cloud:
    config:
      server:
        git:
          username: 13510350350
          uri: https://gitee.com/chenyuhe001/spring-cloud-config-server.git
          password: Ab123456
server:
  port: 9092
eureka:
  client:
    service-url:
      defaultZone: http://192.168.80.160:8761/eureka



